version: "3"

services:
  app:
    container_name: bookmobile
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./"
        target: "/root/projects"
