// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_borrowBook from "./routes/api/borrowBook.ts";
import * as $api_fetchBooks from "./routes/api/fetchBooks.ts";
import * as $api_logIn from "./routes/api/logIn.ts";
import * as $api_registerBook from "./routes/api/registerBook.ts";
import * as $api_signUp from "./routes/api/signUp.ts";
import * as $index from "./routes/index.tsx";
import * as $loginPage from "./routes/loginPage.tsx";
import * as $mainPage from "./routes/mainPage.tsx";
import * as $signUpPage from "./routes/signUpPage.tsx";
import * as $BookPopup from "./islands/BookPopup.tsx";
import * as $BooksTab from "./islands/BooksTab.tsx";
import * as $Card from "./islands/Card.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $Main from "./islands/Main.tsx";
import * as $RegisterBookTab from "./islands/RegisterBookTab.tsx";
import * as $RegisterPopup from "./islands/RegisterPopup.tsx";
import * as $Scan from "./islands/Scan.tsx";
import * as $SignUp from "./islands/SignUp.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/borrowBook.ts": $api_borrowBook,
    "./routes/api/fetchBooks.ts": $api_fetchBooks,
    "./routes/api/logIn.ts": $api_logIn,
    "./routes/api/registerBook.ts": $api_registerBook,
    "./routes/api/signUp.ts": $api_signUp,
    "./routes/index.tsx": $index,
    "./routes/loginPage.tsx": $loginPage,
    "./routes/mainPage.tsx": $mainPage,
    "./routes/signUpPage.tsx": $signUpPage,
  },
  islands: {
    "./islands/BookPopup.tsx": $BookPopup,
    "./islands/BooksTab.tsx": $BooksTab,
    "./islands/Card.tsx": $Card,
    "./islands/Login.tsx": $Login,
    "./islands/Main.tsx": $Main,
    "./islands/RegisterBookTab.tsx": $RegisterBookTab,
    "./islands/RegisterPopup.tsx": $RegisterPopup,
    "./islands/Scan.tsx": $Scan,
    "./islands/SignUp.tsx": $SignUp,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
